spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/iaas?useSSL=false
    username: root
    password: chen19940318
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8088
